#!/usr/bin/env python

import rospy

class RosTopicHzTimeout:

    def __init__(self):


        rospy.init_node('rostopic_hz_timeout',anonymous=True)

        topic = rospy.get_param('~topic')
        timeout = rospy.get_param('~timeout', 1.)

        self.callback_count = 0

        sub = rospy.Subscriber(topic, rospy.AnyMsg, self.callbackHz)

        start_time = rospy.Time.now()

        rospy.sleep(timeout)

        print float(self.callback_count)/timeout

        if self.callback_count == 0:
          exit(1)

    def callbackHz(self, msg):

        self.callback_count += 1

if __name__ == '__main__':

    RosTopicHzTimeout()

