"""autogenerated by genpy from agvc_gps/ConvertGPSOriginRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import nav_msgs.msg
import std_msgs.msg

class ConvertGPSOriginRequest(genpy.Message):
  _md5sum = "cf57bce69c1bcec99f1cf1de90e3fbc7"
  _type = "agvc_gps/ConvertGPSOriginRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
nav_msgs/Odometry gps_global

================================================================================
MSG: nav_msgs/Odometry
# This represents an estimate of a position and velocity in free space.  
# The pose in this message should be specified in the coordinate frame given by header.frame_id.
# The twist in this message should be specified in the coordinate frame given by the child_frame_id
Header header
string child_frame_id
geometry_msgs/PoseWithCovariance pose
geometry_msgs/TwistWithCovariance twist

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['gps_global']
  _slot_types = ['nav_msgs/Odometry']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gps_global

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConvertGPSOriginRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.gps_global is None:
        self.gps_global = nav_msgs.msg.Odometry()
    else:
      self.gps_global = nav_msgs.msg.Odometry()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.gps_global.header.seq, _x.gps_global.header.stamp.secs, _x.gps_global.header.stamp.nsecs))
      _x = self.gps_global.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.gps_global.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.gps_global.pose.pose.position.x, _x.gps_global.pose.pose.position.y, _x.gps_global.pose.pose.position.z, _x.gps_global.pose.pose.orientation.x, _x.gps_global.pose.pose.orientation.y, _x.gps_global.pose.pose.orientation.z, _x.gps_global.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.gps_global.pose.covariance))
      _x = self
      buff.write(_struct_6d.pack(_x.gps_global.twist.twist.linear.x, _x.gps_global.twist.twist.linear.y, _x.gps_global.twist.twist.linear.z, _x.gps_global.twist.twist.angular.x, _x.gps_global.twist.twist.angular.y, _x.gps_global.twist.twist.angular.z))
      buff.write(_struct_36d.pack(*self.gps_global.twist.covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.gps_global is None:
        self.gps_global = nav_msgs.msg.Odometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.gps_global.header.seq, _x.gps_global.header.stamp.secs, _x.gps_global.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_global.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.gps_global.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_global.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.gps_global.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.gps_global.pose.pose.position.x, _x.gps_global.pose.pose.position.y, _x.gps_global.pose.pose.position.z, _x.gps_global.pose.pose.orientation.x, _x.gps_global.pose.pose.orientation.y, _x.gps_global.pose.pose.orientation.z, _x.gps_global.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.gps_global.pose.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.gps_global.twist.twist.linear.x, _x.gps_global.twist.twist.linear.y, _x.gps_global.twist.twist.linear.z, _x.gps_global.twist.twist.angular.x, _x.gps_global.twist.twist.angular.y, _x.gps_global.twist.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.gps_global.twist.covariance = _struct_36d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.gps_global.header.seq, _x.gps_global.header.stamp.secs, _x.gps_global.header.stamp.nsecs))
      _x = self.gps_global.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.gps_global.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.gps_global.pose.pose.position.x, _x.gps_global.pose.pose.position.y, _x.gps_global.pose.pose.position.z, _x.gps_global.pose.pose.orientation.x, _x.gps_global.pose.pose.orientation.y, _x.gps_global.pose.pose.orientation.z, _x.gps_global.pose.pose.orientation.w))
      buff.write(self.gps_global.pose.covariance.tostring())
      _x = self
      buff.write(_struct_6d.pack(_x.gps_global.twist.twist.linear.x, _x.gps_global.twist.twist.linear.y, _x.gps_global.twist.twist.linear.z, _x.gps_global.twist.twist.angular.x, _x.gps_global.twist.twist.angular.y, _x.gps_global.twist.twist.angular.z))
      buff.write(self.gps_global.twist.covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.gps_global is None:
        self.gps_global = nav_msgs.msg.Odometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.gps_global.header.seq, _x.gps_global.header.stamp.secs, _x.gps_global.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_global.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.gps_global.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_global.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.gps_global.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.gps_global.pose.pose.position.x, _x.gps_global.pose.pose.position.y, _x.gps_global.pose.pose.position.z, _x.gps_global.pose.pose.orientation.x, _x.gps_global.pose.pose.orientation.y, _x.gps_global.pose.pose.orientation.z, _x.gps_global.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.gps_global.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.gps_global.twist.twist.linear.x, _x.gps_global.twist.twist.linear.y, _x.gps_global.twist.twist.linear.z, _x.gps_global.twist.twist.angular.x, _x.gps_global.twist.twist.angular.y, _x.gps_global.twist.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.gps_global.twist.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
_struct_6d = struct.Struct("<6d")
_struct_36d = struct.Struct("<36d")
"""autogenerated by genpy from agvc_gps/ConvertGPSOriginResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import nav_msgs.msg
import std_msgs.msg

class ConvertGPSOriginResponse(genpy.Message):
  _md5sum = "2042545c1dd7b502071c6aa6c6444bb9"
  _type = "agvc_gps/ConvertGPSOriginResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """nav_msgs/Odometry gps_local



================================================================================
MSG: nav_msgs/Odometry
# This represents an estimate of a position and velocity in free space.  
# The pose in this message should be specified in the coordinate frame given by header.frame_id.
# The twist in this message should be specified in the coordinate frame given by the child_frame_id
Header header
string child_frame_id
geometry_msgs/PoseWithCovariance pose
geometry_msgs/TwistWithCovariance twist

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['gps_local']
  _slot_types = ['nav_msgs/Odometry']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gps_local

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConvertGPSOriginResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.gps_local is None:
        self.gps_local = nav_msgs.msg.Odometry()
    else:
      self.gps_local = nav_msgs.msg.Odometry()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.gps_local.header.seq, _x.gps_local.header.stamp.secs, _x.gps_local.header.stamp.nsecs))
      _x = self.gps_local.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.gps_local.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.gps_local.pose.pose.position.x, _x.gps_local.pose.pose.position.y, _x.gps_local.pose.pose.position.z, _x.gps_local.pose.pose.orientation.x, _x.gps_local.pose.pose.orientation.y, _x.gps_local.pose.pose.orientation.z, _x.gps_local.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.gps_local.pose.covariance))
      _x = self
      buff.write(_struct_6d.pack(_x.gps_local.twist.twist.linear.x, _x.gps_local.twist.twist.linear.y, _x.gps_local.twist.twist.linear.z, _x.gps_local.twist.twist.angular.x, _x.gps_local.twist.twist.angular.y, _x.gps_local.twist.twist.angular.z))
      buff.write(_struct_36d.pack(*self.gps_local.twist.covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.gps_local is None:
        self.gps_local = nav_msgs.msg.Odometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.gps_local.header.seq, _x.gps_local.header.stamp.secs, _x.gps_local.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_local.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.gps_local.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_local.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.gps_local.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.gps_local.pose.pose.position.x, _x.gps_local.pose.pose.position.y, _x.gps_local.pose.pose.position.z, _x.gps_local.pose.pose.orientation.x, _x.gps_local.pose.pose.orientation.y, _x.gps_local.pose.pose.orientation.z, _x.gps_local.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.gps_local.pose.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.gps_local.twist.twist.linear.x, _x.gps_local.twist.twist.linear.y, _x.gps_local.twist.twist.linear.z, _x.gps_local.twist.twist.angular.x, _x.gps_local.twist.twist.angular.y, _x.gps_local.twist.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.gps_local.twist.covariance = _struct_36d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.gps_local.header.seq, _x.gps_local.header.stamp.secs, _x.gps_local.header.stamp.nsecs))
      _x = self.gps_local.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.gps_local.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.gps_local.pose.pose.position.x, _x.gps_local.pose.pose.position.y, _x.gps_local.pose.pose.position.z, _x.gps_local.pose.pose.orientation.x, _x.gps_local.pose.pose.orientation.y, _x.gps_local.pose.pose.orientation.z, _x.gps_local.pose.pose.orientation.w))
      buff.write(self.gps_local.pose.covariance.tostring())
      _x = self
      buff.write(_struct_6d.pack(_x.gps_local.twist.twist.linear.x, _x.gps_local.twist.twist.linear.y, _x.gps_local.twist.twist.linear.z, _x.gps_local.twist.twist.angular.x, _x.gps_local.twist.twist.angular.y, _x.gps_local.twist.twist.angular.z))
      buff.write(self.gps_local.twist.covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.gps_local is None:
        self.gps_local = nav_msgs.msg.Odometry()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.gps_local.header.seq, _x.gps_local.header.stamp.secs, _x.gps_local.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_local.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.gps_local.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps_local.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.gps_local.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.gps_local.pose.pose.position.x, _x.gps_local.pose.pose.position.y, _x.gps_local.pose.pose.position.z, _x.gps_local.pose.pose.orientation.x, _x.gps_local.pose.pose.orientation.y, _x.gps_local.pose.pose.orientation.z, _x.gps_local.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.gps_local.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.gps_local.twist.twist.linear.x, _x.gps_local.twist.twist.linear.y, _x.gps_local.twist.twist.linear.z, _x.gps_local.twist.twist.angular.x, _x.gps_local.twist.twist.angular.y, _x.gps_local.twist.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.gps_local.twist.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
_struct_6d = struct.Struct("<6d")
_struct_36d = struct.Struct("<36d")
class ConvertGPSOrigin(object):
  _type          = 'agvc_gps/ConvertGPSOrigin'
  _md5sum = 'ecd21f5fc40d2acf04caba644024bc82'
  _request_class  = ConvertGPSOriginRequest
  _response_class = ConvertGPSOriginResponse
