#!/bin/bash

# USAGE:  ./tmuxprocmon [procmon config file]
# this requires tmux and htop to be installed
#  sudo apt-get install tmux htop

# Thanks to Stanley Lam for letting us use procman
# which he developed.

source $HOME/.bashrc
#source $HOME/owr_software/rover/devel/setup.bash
export TMUXPROCMON=1
cd "$(dirname "$0")"

tmux new-session -d -s prm "env ./procmon.py $1"
#tmux rename-window 'procmon'
tmux split-window -h -d 'exec tail -n 0 -F /tmp/procmon.log'
tmux split-window -v -t 0 -p 20 -d 'exec htop'
tmux source-file tmuxprocmon.conf
tmux attach-session -t prm
#tmux -2 attach-session -t prm
