#!/bin/bash
if [ ! -f /tmp/procmon.log ]; then
  rm ~/.ros/*.pid &> /dev/null
  touch /tmp/procmon.log
fi

PS1=" "
export PS1

source ~/.bashrc
source ~/owr_software/gui/devel/setup.bash
export ROS_MASTER_URI=http://192.168.1.10:11311

cd `dirname $0`

echo Server Process Monitor launched `date` >> /tmp/procmon.log

nohup env ./serverprocmon.py &

if [ -z "$SSH_CLIENT" ]; then
#  env gnome-terminal --window --full-screen -e './serverprocmon.py' 
else
#  ./tmuxprocmon procmon.conf
fi

