#!/bin/bash

# USAGE:  ./tmuxprocmon [procmon config file]
# this requires tmux and htop to be installed
#  sudo apt-get install tmux htop

# Thanks to Stanley Lam for letting us use procman
# which he developed.

source $HOME/.bashrc
export TMUXPROCMON=1
cd "$(dirname "$0")"
source ../devel/setup.bash

tmux new-session -d -s prm2 "env ./procmon.py $1"
#tmux rename-window 'procmon'
tmux split-window -h -t prm2 -d 'exec tail -n 0 -F /tmp/procmon.log'
tmux split-window -v -t prm2 -p 20 -d 'exec htop'
tmux source-file tmuxprocmon.conf
tmux attach-session -t prm2
#tmux -2 attach-session -t prm
